export interface CountryCode {
    code: string;
    name: string;
    dialCode: string;
  }
  /*OLD */
  /*
  export const countries: CountryCode[] = [
    { code: "FR", name: "France", dialCode: "+33" },
    { code: "US", name: "United States", dialCode: "+1" },
    { code: "UK", name: "United Kingdom", dialCode: "+44" },
    { code: "CA", name: "Canada", dialCode: "+1" },
    { code: "AU", name: "Australia", dialCode: "+61" },
    { code: "DE", name: "Germany", dialCode: "+49" },
    { code: "IN", name: "India", dialCode: "+91" },
    { code: "BR", name: "Brazil", dialCode: "+55" },
    { code: "CN", name: "China", dialCode: "+86" },
    { code: "JP", name: "Japan", dialCode: "+81" },
    { code: "MX", name: "Mexico", dialCode: "+52" },
    { code: "IT", name: "Italy", dialCode: "+39" },
    { code: "ES", name: "Spain", dialCode: "+34" },
    { code: "RU", name: "Russia", dialCode: "+7" },
    { code: "ZA", name: "South Africa", dialCode: "+27" },
  ];*/

 export const countries: CountryCode[] = [
  { code: "AD", name: "Andorra", dialCode: "+376" },
  { code: "AL", name: "Albania", dialCode: "+355" },
  { code: "AM", name: "Armenia", dialCode: "+374" },
  { code: "AT", name: "Austria", dialCode: "+43" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { code: "BE", name: "Belgium", dialCode: "+32" },
  { code: "BG", name: "Bulgaria", dialCode: "+359" },
  { code: "BY", name: "Belarus", dialCode: "+375" },
  { code: "CH", name: "Switzerland", dialCode: "+41" },
  { code: "CY", name: "Cyprus", dialCode: "+357" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420" },
  { code: "DE", name: "Germany", dialCode: "+49" },
  { code: "DK", name: "Denmark", dialCode: "+45" },
  { code: "EE", name: "Estonia", dialCode: "+372" },
  { code: "ES", name: "Spain", dialCode: "+34" },
  { code: "FI", name: "Finland", dialCode: "+358" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "GB", name: "United Kingdom", dialCode: "+44" },
  { code: "GE", name: "Georgia", dialCode: "+995" },
  { code: "GR", name: "Greece", dialCode: "+30" },
  { code: "HR", name: "Croatia", dialCode: "+385" },
  { code: "HU", name: "Hungary", dialCode: "+36" },
  { code: "IE", name: "Ireland", dialCode: "+353" },
  { code: "IS", name: "Iceland", dialCode: "+354" },
  { code: "IT", name: "Italy", dialCode: "+39" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423" },
  { code: "LT", name: "Lithuania", dialCode: "+370" },
  { code: "LU", name: "Luxembourg", dialCode: "+352" },
  { code: "LV", name: "Latvia", dialCode: "+371" },
  { code: "MC", name: "Monaco", dialCode: "+377" },
  { code: "MD", name: "Moldova", dialCode: "+373" },
  { code: "ME", name: "Montenegro", dialCode: "+382" },
  { code: "MK", name: "North Macedonia", dialCode: "+389" },
  { code: "MT", name: "Malta", dialCode: "+356" },
  { code: "NL", name: "Netherlands", dialCode: "+31" },
  { code: "NO", name: "Norway", dialCode: "+47" },
  { code: "PL", name: "Poland", dialCode: "+48" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "RO", name: "Romania", dialCode: "+40" },
  { code: "RS", name: "Serbia", dialCode: "+381" },
  { code: "RU", name: "Russia", dialCode: "+7" },
  { code: "SE", name: "Sweden", dialCode: "+46" },
  { code: "SI", name: "Slovenia", dialCode: "+386" },
  { code: "SK", name: "Slovakia", dialCode: "+421" },
  { code: "SM", name: "San Marino", dialCode: "+378" },
  { code: "TR", name: "Turkey", dialCode: "+90" },
  { code: "UA", name: "Ukraine", dialCode: "+380" },
  { code: "VA", name: "Vatican City", dialCode: "+379" },
  { code: "XK", name: "Kosovo", dialCode: "+383" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966" },
];
